### PR TITLE
ci.yml: bump version

### PR DESCRIPTION
**Pull request by kbdharun**
## Changes

- Bump actions/checkout version to v3.
- Replace archived action https://github.com/actions/setup-elixir with https://github.com/erlef/setup-beam

### CODE REVIEW

**Review by owenvoke — APPROVED** [review]
LGTM! (Damn, `setup-beam` is really weird as a name)

**Comment by kbdharun** [comment]
> LGTM! (Damn, `setup-beam` is really weird as a name)

True lol 🤣

**Review by MasterOdin — APPROVED** [review]

**Comment by kbdharun** [comment]
I notice the action is struck at this

```
Requested labels: ubuntu-18.04
Job defined at: tldr-pages/extldr/.github/workflows/ci.yml@refs/heads/master
Waiting for a runner to pick up this job...
```

What could cause this?

**Comment by kbdharun** [comment]
One action seems to be still running after an hour waiting for the runner.

**Pull request merged**
