### PR TITLE
Update references to the repository

### LINKED ISSUE #13: Change all the references to old repository to the new location in tldr-pages organization
Due this repository has been transferred to @tldr-pages, it is necessary to perform some changes:

- [x] Change references to ivanhercaz/extldr in the badges of the README.
- [x] Check if Travis CI and another tools continuos to work fine with this repository after change the old reference, if not, it should be fixed. It is possible that for this I will need to be administrator of this repository.
- [x] Change links to the old reference of the repository to this new one to avoid redirects.

Although this is not exactly a documentation issue, I think this one is the best one to organize this issue. If someone have a suggestion, it would be awesome if you apply it or discuss about it.

### PR DESCRIPTION
**Pull request by owenvoke**
This is part of #13, note that I think we need to add org authentication for Coveralls, etc. for the badges to work. 👍

### CODE REVIEW

**Comment by ivanhercaz** [comment]
Wow! You're really awesome @owenvoke, thank you for update the references :heart: I am going to check the reason of the build failed.

**Comment by ivanhercaz** [comment]
All right, I understand the reason of the fail.

> The command "mix coveralls.travis" exited with 1.

As I include Coveralls in Travis, it seems this command doesn't run successfully, probably due it is necessary to configure Coveralls again. I will take a look.

**Comment by ivanhercaz** [comment]
The build [failed yet](https://travis-ci.com/github/tldr-pages/extldr/builds/165817310) :/ That seems strange.

**Comment by owenvoke** [comment]
Yeah, I hadn't actually enabled it on this repository. _sigh_ Coveralls should now work 🤦

~~Quick question, do we need to setup the `repo_token` for Travis? 🤔~~
Guess not, it's passed 🎉

**Comment by ivanhercaz** [comment]
> Yeah, I hadn't actually enabled it on this repository. _sigh_ Coveralls should now work 

Okay! It has sense, now it works really fine. Alls builds are passing the tests.
 
> Quick question, do we need to setup the `repo_token` for Travis?

If I am honest, @owenvoke, I didn't remember to setup any `repo_token` for Travis. I think it is just necessary when it is a private repository.

**Comment by ivanhercaz** [comment]
Nice! It is just necessary to setup Codacy and everything will be as before the transfer.

**Review by ivanhercaz — APPROVED** [review]
It looks... awesome to me! Thank you very much for change all the old references, @owenvoke. We have two options now:

1. Wait for someone of the organization grants to Codacy the access to this repository to have the badges working.
2. Merge this PR and then wait, although the link of the Codacy badge will returns an not found error.

**Comment by owenvoke** [comment]
I've also enabled Codacy now 👌  Looks like the badge needs to be updated though to:
`[Codacy Badge](https://www.codacy.com/gh/tldr-pages/extldr)`

[Codacy Badge](https://www.codacy.com/gh/tldr-pages/extldr)
If anyone wants to update my PR to amend that, feel free. Or I'll do it first thing tomorrow. :+1:

**Comment by ivanhercaz** [comment]
> I've also enabled Codacy now  Looks like the badge needs to be updated though to:
> `[Codacy Badge](https://www.codacy.com/gh/tldr-pages/extldr)`
> 
> [Codacy Badge](https://www.codacy.com/gh/tldr-pages/extldr)
> If anyone wants to update my PR to amend that, feel free. Or I'll do it first thing tomorrow.

Awesome! I will update the PR and then merge it. Again, thank you very much, @owenvoke, for all your help with this issue.

**Comment by ivanhercaz** [comment]
Nice! Now it is being running the 

> [CLA assistant check](https://cla-assistant.io/tldr-pages/extldr?pullRequest=14)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/tldr-pages/extldr?pullRequest=14) before we can accept your contribution.
> **1** out of **2** committers have signed the CLA.
> 
>  ivanhercaz
>  owenvoke
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/tldr-pages/extldr?pullRequest=14) it.

@owenvoke, I prefer to wait until you sign the CLA. No hurry for this, so this PR can be merged tomorrow (feel free to merge it by yourself). I will try to work in another issues tonight.

**Comment by owenvoke** [comment]
Signed! So you're free to merge. :ok_hand: I should probably get some sleep though.

**Comment by ivanhercaz** [comment]
> Signed! So you're free to merge.

Thank you very much! I am going to merge it :tada:

> I should probably get some sleep though.

I hope you rest and have sweet dreams!

**Pull request merged**
